import os
import glob
import sys  
import inflect
from datetime import datetime

def migration_create(name: str, console):
    """
    Create a unique database migration class file by checking duplicate __tablename__.
    Ensures input is normalized (singularized then pluralized) to avoid duplication.
    """
    migrations_dir = "database/migrations"
    os.makedirs(migrations_dir, exist_ok=True)
    
    name_lower = name.lower()
    p = inflect.engine()
    
    # -------------------------------------------------------------------------
    # Normalize Name: Convert input to singular first, then pluralize for table
    # -------------------------------------------------------------------------
    singular_name = p.singular_noun(name_lower)
    if not singular_name:
        singular_name = name_lower
        
    table_name = p.plural(singular_name)
    class_name = f"{singular_name.capitalize()}Table"
    
    # -------------------------------------------------------------------------
    # Check 1: Verify if __tablename__ already exists in any migration file
    # -------------------------------------------------------------------------
    existing_migration_files = glob.glob(f"{migrations_dir}/*.py")
    
    for file_path in existing_migration_files:
        if os.path.basename(file_path) in ["base.py", "__init__.py"]:
            continue
            
        try:
            with open(file_path, "r") as f:
                file_content = f.read()
                if f'__tablename__ = "{table_name}"' in file_content or f"__tablename__ = '{table_name}'" in file_content:
                    console.print(f"[bold red]❌ Error:[/bold red] Table name [yellow]'{table_name}'[/yellow] already exists in a migration!")
                    console.print(f"Conflict found in: [dim]{file_path}[/dim]")
                    # Using sys.exit(1) to completely crash/stop execution right here
                    sys.exit(1) 
        except Exception:
            pass

    # -------------------------------------------------------------------------
    # File Creation: This will ONLY run if no duplicate table was found above
    # -------------------------------------------------------------------------
    timestamp = datetime.now().strftime("%Y_%m_%d_%H%M%S")
    file_base_name = f"{singular_name}_{timestamp}_table"
    filename = f"{migrations_dir}/{file_base_name}.py"
    
    migration_template = f"""# Migration generated by Karigor at {datetime.now()}
from sqlalchemy import Column, Integer, DateTime
from sqlalchemy.sql import func
from config.meta_data import Base 

class {class_name}(Base):
    __tablename__ = "{table_name}" 

    id = Column(Integer, primary_key=True, index=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())
"""
    
    with open(filename, "w") as f:
        f.write(migration_template)
        
    console.print(f"[bold green]✔[/bold green] Migration created: [yellow]{filename}[/yellow]")

    # -------------------------------------------------------------------------
    # Check 2: Register inside base.py avoiding duplicate imports
    # -------------------------------------------------------------------------
    base_file_path = f"{migrations_dir}/base.py"
    import_line = f"from database.migrations.{file_base_name} import {class_name}\n"
    
    if not os.path.exists(base_file_path):
        with open(base_file_path, "w") as base_file:
            base_file.write("# Generated by Karigor CLI - Master Migration List\n")
            base_file.write(import_line)
        console.print(f"[bold green]✔[/bold green] Registered in: [yellow]{base_file_path}[/yellow]")
    else:
        with open(base_file_path, "r") as base_file:
            content = base_file.read()
            
        if f"import {class_name}" in content:
            console.print(f"[bold yellow]⚠ Warning:[/bold yellow] [yellow]{class_name}[/yellow] is already imported in base.py.")
        else:
            with open(base_file_path, "a") as base_file:
                base_file.write(import_line)
            console.print(f"[bold green]✔[/bold green] Registered in: [yellow]{base_file_path}[/yellow]")