# ফাইলের নাম: karigor/alembic/modify_alembic_env.py
import os

def modify_alembic_env(console):
    """Overwrites alembic/env.py with the exact user-defined template"""
    env_py_path = os.path.join("alembic", "env.py")
    
    # ট্রিপল কোটের ঝামেলা এড়াতে লিস্ট এবং জয়েন ব্যবহার করে নিখুঁত টেমপ্লেট তৈরি
    env_lines = [
        "from logging.config import fileConfig",
        "",
        "from sqlalchemy import engine_from_config",
        "from sqlalchemy import pool",
        "",
        "from alembic import context",
        "",
        "from config.env_setting import settings",
        "from config.meta_data import Base",
        "",
        "# this is the Alembic Config object, which provides",
        "# access to the values within the .ini file in use.",
        "config = context.config",
        "",
        'config.set_main_option("sqlalchemy.url", settings.DATABASE_URL)',
        "",
        "# Interpret the config file for Python logging.",
        "# This line sets up loggers basically.",
        "if config.config_file_name is not None:",
        "    fileConfig(config.config_file_name)",
        "",
        "# add your model's MetaData object here",
        "# for 'autogenerate' support",
        "# from myapp import mymodel",
        "# target_metadata = mymodel.Base.metadata",
        "target_metadata = Base.metadata",
        "",
        "# other values from the config, defined by the needs of env.py,",
        "# can be acquired:",
        '# my_important_option = config.get_main_option("my_important_option")',
        "# ... etc.",
        "",
        "",
        "def run_migrations_offline() -> None:",
        '    """Run migrations in \'offline\' mode.',
        "",
        "    This configures the context with just a URL",
        "    and not an Engine, though an Engine is acceptable",
        "    here as well.  By skipping the Engine creation",
        "    we don't even need a DBAPI to be available.",
        "",
        "    Calls to context.execute() here emit the given string to the",
        "    script output.",
        "",
        '    """',
        '    url = config.get_main_option("sqlalchemy.url")',
        "    context.configure(",
        "        url=url,",
        "        target_metadata=target_metadata,",
        "        literal_binds=True,",
        '        dialect_opts={"paramstyle": "named"},',
        "    )",
        "",
        "    with context.begin_transaction():",
        "        context.run_migrations()",
        "",
        "",
        "def run_migrations_online() -> None:",
        '    """Run migrations in \'online\' mode.',
        "",
        "    In this scenario we need to create an Engine",
        "    and associate a connection with the context.",
        "",
        '    """',
        "    connectable = engine_from_config(",
        "        config.get_section(config.config_ini_section, {}),",
        '        prefix="sqlalchemy.",',
        "        poolclass=pool.NullPool,",
        "    )",
        "",
        "    with connectable.connect() as connection:",
        "        context.configure(",
        "            connection=connection, target_metadata=target_metadata",
        "        )",
        "",
        "        with context.begin_transaction():",
        "            context.run_migrations()",
        "",
        "",
        "if context.is_offline_mode():",
        "    run_migrations_offline()",
        "else:",
        "    run_migrations_online()",
        ""
    ]
    
    env_content = "\n".join(env_lines)
    
    # ফাইলটি নতুন করে রাইট করা
    with open(env_py_path, "w", encoding="utf-8") as f:
        f.write(env_content)
